### PR TITLE
Fixes #110, #24, #101: Use httptoolkit/frida-android-unpinning

### LINKED ISSUE #110: Replace objection with httptoolkit/frida-android-unpinning
As per https://github.com/tweaselORG/meta/issues/16, we want to replace objection with https://github.com/httptoolkit/frida-android-unpinning:

> I'd say we do switch to the HT script (it seems more actively maintained, is not worse and maybe even a little better than objection, and it saves us from all the trouble we had with keeping objection's process around (https://github.com/tweaselORG/appstraction/issues/101, https://github.com/tweaselORG/appstraction/issues/24)).

### PR DESCRIPTION
**Pull request by baltpeter**

### CODE REVIEW

**Review by zner0L — CHANGES_REQUESTED** [review]
I am pretty happy with this and it does work if I run it in the development directory, but if I build it and run the example with the built library, I get the following error:

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: Script(line 698): SyntaxError: unsupported keyword: export]

Node.js v18.14.2
```

I am guessing this relates to the new module syntax you introduced in the `tsconfig.json`. I verified my setup works with the current `main` branch.

**Comment by baltpeter** [comment]
The problem is that Parcel builds the unpinning script instead of treating it as a text file. It adds:

```js
export {$ee1b1628d2dcda72$exports as default};
```

The JS engine Frida uses doesn't understand that, thus the error.

**Comment by baltpeter** [comment]
[Parcel _does_ support inlining files without transforming them](https://parceljs.org/features/bundle-inlining/#inlining-without-transforming). However, for that to work, you need to use [`readFileSync` and `__dirname`](https://parceljs.org/features/node-emulation/#inlining-fs.readfilesync) exactly like this:

```js
const unpinningScript = readFileSync(join(__dirname, 'external', 'frida-android-unpinning.js'), 'utf-8');
```

Using `readFile` from `fs/promises` or `import.meta` instead of `__dirname` does not work.

However, if we _do_ use `__dirname`, we can't run the example scripts through `tsx` anymore. That uses `esbuild` under the hood which doesn't have support for Parcel's `__dirname` hack:

```
/home/benni/coding/JS/tweasel/appstraction/src/android.ts:627
            const unpinningScript = readFileSync(join(__dirname, 'external', 'frida-android-unpinning.js'), 'utf-8');
                                                      ^


ReferenceError: __dirname is not defined
    at Object.startApp (/home/benni/coding/JS/tweasel/appstraction/src/android.ts:627:55)
    at <anonymous> (/home/benni/coding/JS/tweasel/appstraction/examples/android-device.ts:47:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by baltpeter** [comment]
So, we need our own hack. If I rename the file to `frida-android-unpinning.js.txt`, doesn't recognize it as JavaScript anymore and leaves it alone. *shrug*

**Review by zner0L — APPROVED** [review]
Great, now it works!

**Pull request merged**
