### PR TITLE
Fixes #4: Support for installing split APKs

### LINKED ISSUE #4: Installing split APKs
We download Android apps as split APKs. For example, downloading [DB Navigator](https://play.google.com/store/apps/details?id=de.hafas.android.db) using [googleplay](https://github.com/hr8/googleplay) yields the following files:

```
de.hafas.android.db-221000003.apk
de.hafas.android.db-config.de-221000003.apk
de.hafas.android.db-config.mdpi-221000003.apk
de.hafas.android.db-config.x86-221000003.apk
```

These tend to include APKs for different architectures (`de.hafas.android.db-config.x86-221000003.apk` for x86 in this case). We were previously using an x86_64 emulator running Android 11 (API level 30). Here, we could just install all split APKs:

```sh
adb install-multiple *.apk
```

This works even when there are split APKs for architectures not supported by the device/emulator. This seems to have changed with Android 13 (API level 33). Now, running the above command results in an error:

```
adb: failed to finalize session
Failure [INSTALL_FAILED_NO_MATCHING_ABIS: INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
```

We now have to explicitly specify only the parts that are actually supported by the device. So, in this case for an x86_64 emulator:

```sh
adb install-multiple de.hafas.android.db-221000003.apk de.hafas.android.db-config.de-221000003.apk de.hafas.android.db-config.mdpi-221000003.apk
```

That's quite annoying. Hopefully, there is a better way.

**Update**: [I misunderstood things a little here](https://github.com/tweaselORG/appstraction/issues/4#issuecomment-1486968344).

### PR DESCRIPTION
**Pull request by baltpeter**
**This is based on #42.**

### CODE REVIEW

**Comment by baltpeter** [comment]
This PR makes [`path.ts` in CA](https://github.com/tweaselORG/cyanoacrylate/blob/a0b09cf2a0cab5f538df587a31ca9cffa6ca8316/src/path.ts) obsolete. We can just get rid of that once this is merged.

**Comment by baltpeter** [comment]
I noticed a problem with the current implementation that I need to fix before this can be merged: https://github.com/tweaselORG/appstraction/issues/4#issuecomment-1486959727

**Comment by baltpeter** [comment]
Fixed now.

**Review by zner0L — DISMISSED** [review]
Really nice, thank you!

**Pull request merged**
